//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomestayApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<int> SoTienDatTruoc { get; set; }
        public string DonVi { get; set; }
    }
}
