//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomestayApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDANGKI
    {
        public string MaPhieuDangKi { get; set; }
        public string MaKhachHang { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
    }
}
