//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomestayApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        public string MaPhong { get; set; }
        public string TenPhong { get; set; }
        public string TinhTrang { get; set; }
        public string MaLoaiPhong { get; set; }
        public Nullable<int> GiaPhong { get; set; }
        public string DonVi { get; set; }
    }
}
