//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomestayApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string HoTen { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public string TaiKhoan1 { get; set; }
        public string Matkhau { get; set; }
    }
}
